In [1]:
import numpy as np

In [2]:
list1=[1,3,5,7,8]
arr1=np.array(list1)

In [3]:
print(list1)

[1, 3, 5, 7, 8]


In [4]:
type(arr1)

numpy.ndarray

In [5]:
type(list1)

list

In [6]:
arr2=np.array([1,2,3,4])
print(arr2)

[1 2 3 4]


In [7]:
arr3=np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
print(arr3.shape)

(2, 4)


In [10]:
arr4=arr3.reshape((4,2))

In [11]:
arr4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
arr5=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
arr6=np.eye(3)

In [20]:
print(arr6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
print(arr1.ndim)

1


In [25]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
np.random.rand()

0.6046965235870495

In [30]:
np.random.randint(1,1000)

536

In [31]:
print(arr4.min())
print(arr4.max())

1
8


In [32]:
print(np.__version__)

1.19.5


In [33]:
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]


In [34]:
print(arr3[0,1])

2


In [35]:
print(arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
print(arr5[2,1])

10


In [41]:
arr6=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [42]:
print(arr6)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [43]:
arr6.ndim

3

In [44]:
print(arr6[0,1,2])

6


In [45]:
print(arr6[1,0,1])

8


In [61]:
print(arr3[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [77]:
print(arr6[0:1])

[[[1 2 3]
  [4 5 6]]]


In [75]:
arr7=np.array([1,2,3,4,5,6])

In [79]:
print(arr7[0:4])

[1 2 3 4]


In [80]:
print(arr6)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [87]:
arr8=np.array([[1,2,3,4,5],[6,7,8,9,10]])


In [105]:
print(arr8[0:2,2:4])

[[3 4]
 [8 9]]


In [98]:
print(arr8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [103]:
arr8.ndim

2

In [106]:
print(arr8[1,2:4])

[8 9]


In [107]:
print(arr6)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [129]:
print(arr6[0:2,0:2,1:3])

[[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


In [130]:
print(arr7)

[1 2 3 4 5 6]


In [131]:
for x in arr7:
    print(x)

1
2
3
4
5
6


In [132]:
print(arr8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [139]:
for x in arr6:
    for x1 in x:
        for x2 in x1:
            print(x2)

1
2
3
4
5
6
7
8
9
10
11
12
